//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.09 at 03:43:40 PM ICT 
//


package com.newexa.cifchild.stub;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AZACCOUNTIDIDEPCLOSETWSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AZACCOUNTIDIDEPCLOSETWSType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NOMINATEDACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CHGFROMREDAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WAIVECHG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gCHARGECODE" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="mCHARGECODE" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="CHARGECODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="CHARGEAMOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="CHGLIQACCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="m" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BENACC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BENNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SKNTXNCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RESIDEYN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NATIONSTATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SKNRECEIVBANK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MUDCLEARED" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SKNRTGS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LOCK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RTGSTXNCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RTGSCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOACCBRANCH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AZACCOUNTIDIDEPCLOSETWSType", propOrder = {
    "nominatedaccount",
    "chgfromredamt",
    "waivechg",
    "gchargecode",
    "benacc",
    "benname",
    "skntxncode",
    "resideyn",
    "nationstatus",
    "sknreceivbank",
    "mudcleared",
    "sknrtgs",
    "lock",
    "rtgstxncode",
    "rtgscode",
    "toaccbranch"
})
public class AZACCOUNTIDIDEPCLOSETWSType {

    @XmlElement(name = "NOMINATEDACCOUNT")
    protected String nominatedaccount;
    @XmlElement(name = "CHGFROMREDAMT")
    protected String chgfromredamt;
    @XmlElement(name = "WAIVECHG")
    protected String waivechg;
    @XmlElement(name = "gCHARGECODE")
    protected AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE gchargecode;
    @XmlElement(name = "BENACC")
    protected String benacc;
    @XmlElement(name = "BENNAME")
    protected String benname;
    @XmlElement(name = "SKNTXNCODE")
    protected String skntxncode;
    @XmlElement(name = "RESIDEYN")
    protected String resideyn;
    @XmlElement(name = "NATIONSTATUS")
    protected String nationstatus;
    @XmlElement(name = "SKNRECEIVBANK")
    protected String sknreceivbank;
    @XmlElement(name = "MUDCLEARED")
    protected String mudcleared;
    @XmlElement(name = "SKNRTGS")
    protected String sknrtgs;
    @XmlElement(name = "LOCK")
    protected String lock;
    @XmlElement(name = "RTGSTXNCODE")
    protected String rtgstxncode;
    @XmlElement(name = "RTGSCODE")
    protected String rtgscode;
    @XmlElement(name = "TOACCBRANCH")
    protected String toaccbranch;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the nominatedaccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMINATEDACCOUNT() {
        return nominatedaccount;
    }

    /**
     * Sets the value of the nominatedaccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMINATEDACCOUNT(String value) {
        this.nominatedaccount = value;
    }

    /**
     * Gets the value of the chgfromredamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHGFROMREDAMT() {
        return chgfromredamt;
    }

    /**
     * Sets the value of the chgfromredamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHGFROMREDAMT(String value) {
        this.chgfromredamt = value;
    }

    /**
     * Gets the value of the waivechg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWAIVECHG() {
        return waivechg;
    }

    /**
     * Sets the value of the waivechg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWAIVECHG(String value) {
        this.waivechg = value;
    }

    /**
     * Gets the value of the gchargecode property.
     * 
     * @return
     *     possible object is
     *     {@link AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE }
     *     
     */
    public AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE getGCHARGECODE() {
        return gchargecode;
    }

    /**
     * Sets the value of the gchargecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE }
     *     
     */
    public void setGCHARGECODE(AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE value) {
        this.gchargecode = value;
    }

    /**
     * Gets the value of the benacc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBENACC() {
        return benacc;
    }

    /**
     * Sets the value of the benacc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBENACC(String value) {
        this.benacc = value;
    }

    /**
     * Gets the value of the benname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBENNAME() {
        return benname;
    }

    /**
     * Sets the value of the benname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBENNAME(String value) {
        this.benname = value;
    }

    /**
     * Gets the value of the skntxncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKNTXNCODE() {
        return skntxncode;
    }

    /**
     * Sets the value of the skntxncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKNTXNCODE(String value) {
        this.skntxncode = value;
    }

    /**
     * Gets the value of the resideyn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESIDEYN() {
        return resideyn;
    }

    /**
     * Sets the value of the resideyn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESIDEYN(String value) {
        this.resideyn = value;
    }

    /**
     * Gets the value of the nationstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONSTATUS() {
        return nationstatus;
    }

    /**
     * Sets the value of the nationstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONSTATUS(String value) {
        this.nationstatus = value;
    }

    /**
     * Gets the value of the sknreceivbank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKNRECEIVBANK() {
        return sknreceivbank;
    }

    /**
     * Sets the value of the sknreceivbank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKNRECEIVBANK(String value) {
        this.sknreceivbank = value;
    }

    /**
     * Gets the value of the mudcleared property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMUDCLEARED() {
        return mudcleared;
    }

    /**
     * Sets the value of the mudcleared property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMUDCLEARED(String value) {
        this.mudcleared = value;
    }

    /**
     * Gets the value of the sknrtgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKNRTGS() {
        return sknrtgs;
    }

    /**
     * Sets the value of the sknrtgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKNRTGS(String value) {
        this.sknrtgs = value;
    }

    /**
     * Gets the value of the lock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCK() {
        return lock;
    }

    /**
     * Sets the value of the lock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCK(String value) {
        this.lock = value;
    }

    /**
     * Gets the value of the rtgstxncode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRTGSTXNCODE() {
        return rtgstxncode;
    }

    /**
     * Sets the value of the rtgstxncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRTGSTXNCODE(String value) {
        this.rtgstxncode = value;
    }

    /**
     * Gets the value of the rtgscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRTGSCODE() {
        return rtgscode;
    }

    /**
     * Sets the value of the rtgscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRTGSCODE(String value) {
        this.rtgscode = value;
    }

    /**
     * Gets the value of the toaccbranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOACCBRANCH() {
        return toaccbranch;
    }

    /**
     * Sets the value of the toaccbranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOACCBRANCH(String value) {
        this.toaccbranch = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="mCHARGECODE" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="CHARGECODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="CHARGEAMOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="CHGLIQACCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="m" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mchargecode"
    })
    public static class GCHARGECODE {

        @XmlElement(name = "mCHARGECODE")
        protected List<AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE.MCHARGECODE> mchargecode;
        @XmlAttribute(name = "g")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger g;

        /**
         * Gets the value of the mchargecode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mchargecode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMCHARGECODE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE.MCHARGECODE }
         * 
         * 
         */
        public List<AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE.MCHARGECODE> getMCHARGECODE() {
            if (mchargecode == null) {
                mchargecode = new ArrayList<AZACCOUNTIDIDEPCLOSETWSType.GCHARGECODE.MCHARGECODE>();
            }
            return this.mchargecode;
        }

        /**
         * Gets the value of the g property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getG() {
            return g;
        }

        /**
         * Sets the value of the g property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setG(BigInteger value) {
            this.g = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="CHARGECODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="CHARGEAMOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="CHGLIQACCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="m" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "chargecode",
            "chargeamount",
            "chgliqacct"
        })
        public static class MCHARGECODE {

            @XmlElement(name = "CHARGECODE")
            protected String chargecode;
            @XmlElement(name = "CHARGEAMOUNT")
            protected String chargeamount;
            @XmlElement(name = "CHGLIQACCT")
            protected String chgliqacct;
            @XmlAttribute(name = "m")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger m;

            /**
             * Gets the value of the chargecode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCHARGECODE() {
                return chargecode;
            }

            /**
             * Sets the value of the chargecode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCHARGECODE(String value) {
                this.chargecode = value;
            }

            /**
             * Gets the value of the chargeamount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCHARGEAMOUNT() {
                return chargeamount;
            }

            /**
             * Sets the value of the chargeamount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCHARGEAMOUNT(String value) {
                this.chargeamount = value;
            }

            /**
             * Gets the value of the chgliqacct property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCHGLIQACCT() {
                return chgliqacct;
            }

            /**
             * Sets the value of the chgliqacct property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCHGLIQACCT(String value) {
                this.chgliqacct = value;
            }

            /**
             * Gets the value of the m property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getM() {
                return m;
            }

            /**
             * Sets the value of the m property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setM(BigInteger value) {
                this.m = value;
            }

        }

    }

}
