//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.09 at 11:13:12 AM ICT 
//


package com.newexa.accountservice.stub;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACCOUNTCLOSUREType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACCOUNTCLOSUREType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CAPITALDATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OPENACTUALBAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OPENCLEAREDBAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ONLINEACTUALBAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ONLINECLEAREDBAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="STANDINGORDERS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UNCLEAREDENTRIES" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALCRINTEREST" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALDRINTEREST" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALPENDINGDR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALCHARGES" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALPENDINGCHG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALTAX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALPENDINGTAX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ACCTLIQUIDATEDTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SETTLEMENTACCT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CHEQUESOS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gBANKCARDS" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="BANKCARDS" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CCCHGSOS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BCBANKSORTCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ACCTLIQUCURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="POSTINGRESTRICT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALPREMIUMAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TOTALACCAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CHARGEABLEAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CLOCHARGETYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CLOCHARGEAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CLOCHTAXTYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CLOCHTAXAMT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CLOCHARGEPOSTED" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CAPINTEREST" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CLOSEONLINE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CLOSEMODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RESERVED6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RESERVED5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RESERVED4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RESERVED3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RESERVED2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RESERVED1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gOVERRIDE" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="OVERRIDE" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RECORDSTATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CURRNO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gINPUTTER" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="INPUTTER" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="gDATETIME" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DATETIME" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AUTHORISER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="COCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DEPTCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AUDITORCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AUDITDATETIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ACCLSNOTE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BAPCLOSING" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACCOUNTCLOSUREType", propOrder = {
    "capitaldate",
    "openactualbal",
    "openclearedbal",
    "onlineactualbal",
    "onlineclearedbal",
    "standingorders",
    "unclearedentries",
    "totalcrinterest",
    "totaldrinterest",
    "totalpendingdr",
    "totalcharges",
    "totalpendingchg",
    "totaltax",
    "totalpendingtax",
    "acctliquidatedto",
    "currency",
    "settlementacct",
    "chequesos",
    "gbankcards",
    "ccchgsos",
    "bcbanksortcode",
    "acctliqucurrency",
    "postingrestrict",
    "totalpremiumamt",
    "totalaccamt",
    "chargeableamt",
    "clochargetype",
    "clochargeamt",
    "clochtaxtype",
    "clochtaxamt",
    "clochargeposted",
    "capinterest",
    "closeonline",
    "ftid",
    "closemode",
    "reserved6",
    "reserved5",
    "reserved4",
    "reserved3",
    "reserved2",
    "reserved1",
    "goverride",
    "recordstatus",
    "currno",
    "ginputter",
    "gdatetime",
    "authoriser",
    "cocode",
    "deptcode",
    "auditorcode",
    "auditdatetime",
    "acclsnote",
    "bapclosing"
})
public class ACCOUNTCLOSUREType {

    @XmlElement(name = "CAPITALDATE")
    protected String capitaldate;
    @XmlElement(name = "OPENACTUALBAL")
    protected String openactualbal;
    @XmlElement(name = "OPENCLEAREDBAL")
    protected String openclearedbal;
    @XmlElement(name = "ONLINEACTUALBAL")
    protected String onlineactualbal;
    @XmlElement(name = "ONLINECLEAREDBAL")
    protected String onlineclearedbal;
    @XmlElement(name = "STANDINGORDERS")
    protected String standingorders;
    @XmlElement(name = "UNCLEAREDENTRIES")
    protected String unclearedentries;
    @XmlElement(name = "TOTALCRINTEREST")
    protected String totalcrinterest;
    @XmlElement(name = "TOTALDRINTEREST")
    protected String totaldrinterest;
    @XmlElement(name = "TOTALPENDINGDR")
    protected String totalpendingdr;
    @XmlElement(name = "TOTALCHARGES")
    protected String totalcharges;
    @XmlElement(name = "TOTALPENDINGCHG")
    protected String totalpendingchg;
    @XmlElement(name = "TOTALTAX")
    protected String totaltax;
    @XmlElement(name = "TOTALPENDINGTAX")
    protected String totalpendingtax;
    @XmlElement(name = "ACCTLIQUIDATEDTO")
    protected String acctliquidatedto;
    @XmlElement(name = "CURRENCY")
    protected String currency;
    @XmlElement(name = "SETTLEMENTACCT")
    protected String settlementacct;
    @XmlElement(name = "CHEQUESOS")
    protected String chequesos;
    @XmlElement(name = "gBANKCARDS")
    protected ACCOUNTCLOSUREType.GBANKCARDS gbankcards;
    @XmlElement(name = "CCCHGSOS")
    protected String ccchgsos;
    @XmlElement(name = "BCBANKSORTCODE")
    protected String bcbanksortcode;
    @XmlElement(name = "ACCTLIQUCURRENCY")
    protected String acctliqucurrency;
    @XmlElement(name = "POSTINGRESTRICT")
    protected String postingrestrict;
    @XmlElement(name = "TOTALPREMIUMAMT")
    protected String totalpremiumamt;
    @XmlElement(name = "TOTALACCAMT")
    protected String totalaccamt;
    @XmlElement(name = "CHARGEABLEAMT")
    protected String chargeableamt;
    @XmlElement(name = "CLOCHARGETYPE")
    protected String clochargetype;
    @XmlElement(name = "CLOCHARGEAMT")
    protected String clochargeamt;
    @XmlElement(name = "CLOCHTAXTYPE")
    protected String clochtaxtype;
    @XmlElement(name = "CLOCHTAXAMT")
    protected String clochtaxamt;
    @XmlElement(name = "CLOCHARGEPOSTED")
    protected String clochargeposted;
    @XmlElement(name = "CAPINTEREST")
    protected String capinterest;
    @XmlElement(name = "CLOSEONLINE")
    protected String closeonline;
    @XmlElement(name = "FTID")
    protected String ftid;
    @XmlElement(name = "CLOSEMODE")
    protected String closemode;
    @XmlElement(name = "RESERVED6")
    protected String reserved6;
    @XmlElement(name = "RESERVED5")
    protected String reserved5;
    @XmlElement(name = "RESERVED4")
    protected String reserved4;
    @XmlElement(name = "RESERVED3")
    protected String reserved3;
    @XmlElement(name = "RESERVED2")
    protected String reserved2;
    @XmlElement(name = "RESERVED1")
    protected String reserved1;
    @XmlElement(name = "gOVERRIDE")
    protected ACCOUNTCLOSUREType.GOVERRIDE goverride;
    @XmlElement(name = "RECORDSTATUS")
    protected String recordstatus;
    @XmlElement(name = "CURRNO")
    protected String currno;
    @XmlElement(name = "gINPUTTER")
    protected ACCOUNTCLOSUREType.GINPUTTER ginputter;
    @XmlElement(name = "gDATETIME")
    protected ACCOUNTCLOSUREType.GDATETIME gdatetime;
    @XmlElement(name = "AUTHORISER")
    protected String authoriser;
    @XmlElement(name = "COCODE")
    protected String cocode;
    @XmlElement(name = "DEPTCODE")
    protected String deptcode;
    @XmlElement(name = "AUDITORCODE")
    protected String auditorcode;
    @XmlElement(name = "AUDITDATETIME")
    protected String auditdatetime;
    @XmlElement(name = "ACCLSNOTE")
    protected String acclsnote;
    @XmlElement(name = "BAPCLOSING")
    protected String bapclosing;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the capitaldate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAPITALDATE() {
        return capitaldate;
    }

    /**
     * Sets the value of the capitaldate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAPITALDATE(String value) {
        this.capitaldate = value;
    }

    /**
     * Gets the value of the openactualbal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPENACTUALBAL() {
        return openactualbal;
    }

    /**
     * Sets the value of the openactualbal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPENACTUALBAL(String value) {
        this.openactualbal = value;
    }

    /**
     * Gets the value of the openclearedbal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPENCLEAREDBAL() {
        return openclearedbal;
    }

    /**
     * Sets the value of the openclearedbal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPENCLEAREDBAL(String value) {
        this.openclearedbal = value;
    }

    /**
     * Gets the value of the onlineactualbal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getONLINEACTUALBAL() {
        return onlineactualbal;
    }

    /**
     * Sets the value of the onlineactualbal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setONLINEACTUALBAL(String value) {
        this.onlineactualbal = value;
    }

    /**
     * Gets the value of the onlineclearedbal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getONLINECLEAREDBAL() {
        return onlineclearedbal;
    }

    /**
     * Sets the value of the onlineclearedbal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setONLINECLEAREDBAL(String value) {
        this.onlineclearedbal = value;
    }

    /**
     * Gets the value of the standingorders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTANDINGORDERS() {
        return standingorders;
    }

    /**
     * Sets the value of the standingorders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTANDINGORDERS(String value) {
        this.standingorders = value;
    }

    /**
     * Gets the value of the unclearedentries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNCLEAREDENTRIES() {
        return unclearedentries;
    }

    /**
     * Sets the value of the unclearedentries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNCLEAREDENTRIES(String value) {
        this.unclearedentries = value;
    }

    /**
     * Gets the value of the totalcrinterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALCRINTEREST() {
        return totalcrinterest;
    }

    /**
     * Sets the value of the totalcrinterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALCRINTEREST(String value) {
        this.totalcrinterest = value;
    }

    /**
     * Gets the value of the totaldrinterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALDRINTEREST() {
        return totaldrinterest;
    }

    /**
     * Sets the value of the totaldrinterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALDRINTEREST(String value) {
        this.totaldrinterest = value;
    }

    /**
     * Gets the value of the totalpendingdr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALPENDINGDR() {
        return totalpendingdr;
    }

    /**
     * Sets the value of the totalpendingdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALPENDINGDR(String value) {
        this.totalpendingdr = value;
    }

    /**
     * Gets the value of the totalcharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALCHARGES() {
        return totalcharges;
    }

    /**
     * Sets the value of the totalcharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALCHARGES(String value) {
        this.totalcharges = value;
    }

    /**
     * Gets the value of the totalpendingchg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALPENDINGCHG() {
        return totalpendingchg;
    }

    /**
     * Sets the value of the totalpendingchg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALPENDINGCHG(String value) {
        this.totalpendingchg = value;
    }

    /**
     * Gets the value of the totaltax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALTAX() {
        return totaltax;
    }

    /**
     * Sets the value of the totaltax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALTAX(String value) {
        this.totaltax = value;
    }

    /**
     * Gets the value of the totalpendingtax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALPENDINGTAX() {
        return totalpendingtax;
    }

    /**
     * Sets the value of the totalpendingtax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALPENDINGTAX(String value) {
        this.totalpendingtax = value;
    }

    /**
     * Gets the value of the acctliquidatedto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCTLIQUIDATEDTO() {
        return acctliquidatedto;
    }

    /**
     * Sets the value of the acctliquidatedto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCTLIQUIDATEDTO(String value) {
        this.acctliquidatedto = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRENCY(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the settlementacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSETTLEMENTACCT() {
        return settlementacct;
    }

    /**
     * Sets the value of the settlementacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSETTLEMENTACCT(String value) {
        this.settlementacct = value;
    }

    /**
     * Gets the value of the chequesos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHEQUESOS() {
        return chequesos;
    }

    /**
     * Sets the value of the chequesos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHEQUESOS(String value) {
        this.chequesos = value;
    }

    /**
     * Gets the value of the gbankcards property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTCLOSUREType.GBANKCARDS }
     *     
     */
    public ACCOUNTCLOSUREType.GBANKCARDS getGBANKCARDS() {
        return gbankcards;
    }

    /**
     * Sets the value of the gbankcards property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTCLOSUREType.GBANKCARDS }
     *     
     */
    public void setGBANKCARDS(ACCOUNTCLOSUREType.GBANKCARDS value) {
        this.gbankcards = value;
    }

    /**
     * Gets the value of the ccchgsos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCCHGSOS() {
        return ccchgsos;
    }

    /**
     * Sets the value of the ccchgsos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCCHGSOS(String value) {
        this.ccchgsos = value;
    }

    /**
     * Gets the value of the bcbanksortcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCBANKSORTCODE() {
        return bcbanksortcode;
    }

    /**
     * Sets the value of the bcbanksortcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCBANKSORTCODE(String value) {
        this.bcbanksortcode = value;
    }

    /**
     * Gets the value of the acctliqucurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCTLIQUCURRENCY() {
        return acctliqucurrency;
    }

    /**
     * Sets the value of the acctliqucurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCTLIQUCURRENCY(String value) {
        this.acctliqucurrency = value;
    }

    /**
     * Gets the value of the postingrestrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSTINGRESTRICT() {
        return postingrestrict;
    }

    /**
     * Sets the value of the postingrestrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSTINGRESTRICT(String value) {
        this.postingrestrict = value;
    }

    /**
     * Gets the value of the totalpremiumamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALPREMIUMAMT() {
        return totalpremiumamt;
    }

    /**
     * Sets the value of the totalpremiumamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALPREMIUMAMT(String value) {
        this.totalpremiumamt = value;
    }

    /**
     * Gets the value of the totalaccamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALACCAMT() {
        return totalaccamt;
    }

    /**
     * Sets the value of the totalaccamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALACCAMT(String value) {
        this.totalaccamt = value;
    }

    /**
     * Gets the value of the chargeableamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHARGEABLEAMT() {
        return chargeableamt;
    }

    /**
     * Sets the value of the chargeableamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHARGEABLEAMT(String value) {
        this.chargeableamt = value;
    }

    /**
     * Gets the value of the clochargetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLOCHARGETYPE() {
        return clochargetype;
    }

    /**
     * Sets the value of the clochargetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLOCHARGETYPE(String value) {
        this.clochargetype = value;
    }

    /**
     * Gets the value of the clochargeamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLOCHARGEAMT() {
        return clochargeamt;
    }

    /**
     * Sets the value of the clochargeamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLOCHARGEAMT(String value) {
        this.clochargeamt = value;
    }

    /**
     * Gets the value of the clochtaxtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLOCHTAXTYPE() {
        return clochtaxtype;
    }

    /**
     * Sets the value of the clochtaxtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLOCHTAXTYPE(String value) {
        this.clochtaxtype = value;
    }

    /**
     * Gets the value of the clochtaxamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLOCHTAXAMT() {
        return clochtaxamt;
    }

    /**
     * Sets the value of the clochtaxamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLOCHTAXAMT(String value) {
        this.clochtaxamt = value;
    }

    /**
     * Gets the value of the clochargeposted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLOCHARGEPOSTED() {
        return clochargeposted;
    }

    /**
     * Sets the value of the clochargeposted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLOCHARGEPOSTED(String value) {
        this.clochargeposted = value;
    }

    /**
     * Gets the value of the capinterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAPINTEREST() {
        return capinterest;
    }

    /**
     * Sets the value of the capinterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAPINTEREST(String value) {
        this.capinterest = value;
    }

    /**
     * Gets the value of the closeonline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLOSEONLINE() {
        return closeonline;
    }

    /**
     * Sets the value of the closeonline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLOSEONLINE(String value) {
        this.closeonline = value;
    }

    /**
     * Gets the value of the ftid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTID() {
        return ftid;
    }

    /**
     * Sets the value of the ftid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTID(String value) {
        this.ftid = value;
    }

    /**
     * Gets the value of the closemode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLOSEMODE() {
        return closemode;
    }

    /**
     * Sets the value of the closemode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLOSEMODE(String value) {
        this.closemode = value;
    }

    /**
     * Gets the value of the reserved6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESERVED6() {
        return reserved6;
    }

    /**
     * Sets the value of the reserved6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESERVED6(String value) {
        this.reserved6 = value;
    }

    /**
     * Gets the value of the reserved5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESERVED5() {
        return reserved5;
    }

    /**
     * Sets the value of the reserved5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESERVED5(String value) {
        this.reserved5 = value;
    }

    /**
     * Gets the value of the reserved4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESERVED4() {
        return reserved4;
    }

    /**
     * Sets the value of the reserved4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESERVED4(String value) {
        this.reserved4 = value;
    }

    /**
     * Gets the value of the reserved3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESERVED3() {
        return reserved3;
    }

    /**
     * Sets the value of the reserved3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESERVED3(String value) {
        this.reserved3 = value;
    }

    /**
     * Gets the value of the reserved2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESERVED2() {
        return reserved2;
    }

    /**
     * Sets the value of the reserved2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESERVED2(String value) {
        this.reserved2 = value;
    }

    /**
     * Gets the value of the reserved1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESERVED1() {
        return reserved1;
    }

    /**
     * Sets the value of the reserved1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESERVED1(String value) {
        this.reserved1 = value;
    }

    /**
     * Gets the value of the goverride property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTCLOSUREType.GOVERRIDE }
     *     
     */
    public ACCOUNTCLOSUREType.GOVERRIDE getGOVERRIDE() {
        return goverride;
    }

    /**
     * Sets the value of the goverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTCLOSUREType.GOVERRIDE }
     *     
     */
    public void setGOVERRIDE(ACCOUNTCLOSUREType.GOVERRIDE value) {
        this.goverride = value;
    }

    /**
     * Gets the value of the recordstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECORDSTATUS() {
        return recordstatus;
    }

    /**
     * Sets the value of the recordstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECORDSTATUS(String value) {
        this.recordstatus = value;
    }

    /**
     * Gets the value of the currno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRNO() {
        return currno;
    }

    /**
     * Sets the value of the currno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRNO(String value) {
        this.currno = value;
    }

    /**
     * Gets the value of the ginputter property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTCLOSUREType.GINPUTTER }
     *     
     */
    public ACCOUNTCLOSUREType.GINPUTTER getGINPUTTER() {
        return ginputter;
    }

    /**
     * Sets the value of the ginputter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTCLOSUREType.GINPUTTER }
     *     
     */
    public void setGINPUTTER(ACCOUNTCLOSUREType.GINPUTTER value) {
        this.ginputter = value;
    }

    /**
     * Gets the value of the gdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link ACCOUNTCLOSUREType.GDATETIME }
     *     
     */
    public ACCOUNTCLOSUREType.GDATETIME getGDATETIME() {
        return gdatetime;
    }

    /**
     * Sets the value of the gdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACCOUNTCLOSUREType.GDATETIME }
     *     
     */
    public void setGDATETIME(ACCOUNTCLOSUREType.GDATETIME value) {
        this.gdatetime = value;
    }

    /**
     * Gets the value of the authoriser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHORISER() {
        return authoriser;
    }

    /**
     * Sets the value of the authoriser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHORISER(String value) {
        this.authoriser = value;
    }

    /**
     * Gets the value of the cocode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOCODE() {
        return cocode;
    }

    /**
     * Sets the value of the cocode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOCODE(String value) {
        this.cocode = value;
    }

    /**
     * Gets the value of the deptcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPTCODE() {
        return deptcode;
    }

    /**
     * Sets the value of the deptcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPTCODE(String value) {
        this.deptcode = value;
    }

    /**
     * Gets the value of the auditorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUDITORCODE() {
        return auditorcode;
    }

    /**
     * Sets the value of the auditorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUDITORCODE(String value) {
        this.auditorcode = value;
    }

    /**
     * Gets the value of the auditdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUDITDATETIME() {
        return auditdatetime;
    }

    /**
     * Sets the value of the auditdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUDITDATETIME(String value) {
        this.auditdatetime = value;
    }

    /**
     * Gets the value of the acclsnote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCLSNOTE() {
        return acclsnote;
    }

    /**
     * Sets the value of the acclsnote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCLSNOTE(String value) {
        this.acclsnote = value;
    }

    /**
     * Gets the value of the bapclosing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAPCLOSING() {
        return bapclosing;
    }

    /**
     * Sets the value of the bapclosing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAPCLOSING(String value) {
        this.bapclosing = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="BANKCARDS" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bankcards"
    })
    public static class GBANKCARDS {

        @XmlElement(name = "BANKCARDS")
        protected List<String> bankcards;
        @XmlAttribute(name = "g")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger g;

        /**
         * Gets the value of the bankcards property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bankcards property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBANKCARDS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getBANKCARDS() {
            if (bankcards == null) {
                bankcards = new ArrayList<String>();
            }
            return this.bankcards;
        }

        /**
         * Gets the value of the g property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getG() {
            return g;
        }

        /**
         * Sets the value of the g property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setG(BigInteger value) {
            this.g = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DATETIME" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datetime"
    })
    public static class GDATETIME {

        @XmlElement(name = "DATETIME")
        protected List<String> datetime;
        @XmlAttribute(name = "g")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger g;

        /**
         * Gets the value of the datetime property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the datetime property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDATETIME().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDATETIME() {
            if (datetime == null) {
                datetime = new ArrayList<String>();
            }
            return this.datetime;
        }

        /**
         * Gets the value of the g property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getG() {
            return g;
        }

        /**
         * Sets the value of the g property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setG(BigInteger value) {
            this.g = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="INPUTTER" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inputter"
    })
    public static class GINPUTTER {

        @XmlElement(name = "INPUTTER")
        protected List<String> inputter;
        @XmlAttribute(name = "g")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger g;

        /**
         * Gets the value of the inputter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the inputter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getINPUTTER().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getINPUTTER() {
            if (inputter == null) {
                inputter = new ArrayList<String>();
            }
            return this.inputter;
        }

        /**
         * Gets the value of the g property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getG() {
            return g;
        }

        /**
         * Sets the value of the g property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setG(BigInteger value) {
            this.g = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="OVERRIDE" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "override"
    })
    public static class GOVERRIDE {

        @XmlElement(name = "OVERRIDE")
        protected List<String> override;
        @XmlAttribute(name = "g")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger g;

        /**
         * Gets the value of the override property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the override property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOVERRIDE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOVERRIDE() {
            if (override == null) {
                override = new ArrayList<String>();
            }
            return this.override;
        }

        /**
         * Gets the value of the g property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getG() {
            return g;
        }

        /**
         * Sets the value of the g property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setG(BigInteger value) {
            this.g = value;
        }

    }

}
